language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
jdk:
- oraclejdk8
before_script:
 - chmod +x gradlew

script:
  - ./gradlew check assembleRelease publishRelease

after_success:
  - git config user.email $GIT_EMAIL
  - git config user.name $GIT_NAME
  - git commit -a -m "Committed by Travis-CI for updated versioncodes"
  - git push origin master